name: Update Table of optimized games
description: This workflow updates the table containing all of the games with optimized settings in the README file and updates the game counter

on:
  workflow_dispatch: # Allows manual trigger
  push: # Only run when changes to optimized settings are pushed
    branches:
      - main
    paths:
      - 'settings/**'

jobs:
  update-table:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gitpython

      - name: Run update game table script
        run: |
          python scripts/update_game_table.py

      - name: Update README Counter
        run: |
          python scripts/game_counter.py

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet README.md || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update game table and counter"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}